server:
  port: 9000
  servlet:
    context-path: /tmall_springboot
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/tmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1725136424
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    show-sql: true